# Generated by Django 5.1.2 on 2025-12-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_money_customuser_score'),
        ('app', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.song'),
        ),
    ]
