# Generated by Django 5.1.2 on 2026-01-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('white', '白'), ('black', '黒')], default='white', max_length=10),
        ),
    ]
