# Generated by Django 5.1.2 on 2026-01-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='score',
            new_name='high_score',
        ),
    ]
