# Generated by Django 5.1.2 on 2026-01-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_score_customuser_high_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='high_score',
        ),
    ]
