# Generated by Django 5.1.2 on 2026-01-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='catchphrase',
            field=models.CharField(choices=[('none', 'なし'), ('beginner', '初心者')], default='none', max_length=255),
        ),
    ]
