# Generated by Django 5.1.2 on 2026-01-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='catchphrase',
            field=models.CharField(choices=[('none', 'なし'), ('beginner', '初心者'), ('intermediate', '中級者')], default='none', max_length=255),
        ),
    ]
