# Generated by Django 5.1.2 on 2026-01-19 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_catchphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCatchphrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catchphrase', models.CharField(choices=[('none', 'なし'), ('beginner', '初心者'), ('intermediate', '中級者')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_catchphrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'catchphrase')},
            },
        ),
    ]
