# Generated by Django 5.1.2 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_purchasedcatchphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='catchphrase',
            field=models.CharField(choices=[('none', 'なし'), ('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasedcatchphrase',
            name='catchphrase',
            field=models.CharField(choices=[('none', 'なし'), ('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], max_length=255),
        ),
    ]
