# Generated by Django 5.1.2 on 2026-01-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開設定'),
        ),
    ]
