# Generated by Django 5.2.8 on 2025-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('mag', models.IntegerField()),
                ('heal_time', models.IntegerField()),
                ('attack_buff', models.IntegerField()),
                ('poison_time', models.IntegerField()),
                ('poison_turn', models.IntegerField()),
                ('sleep_turn', models.IntegerField()),
                ('lv', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('round_turn', models.IntegerField()),
            ],
        ),
    ]
