# Generated by Django 5.1.2 on 2025-12-29 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('karaoke_type', models.CharField(choices=[('DAM', 'DAM'), ('JOY', 'JOYSOUND')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='score_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
