# Generated by Django 5.1.2 on 2025-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scorelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorelog',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
