# Generated by Django 5.1.2 on 2025-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_scorelog_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorelog',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
