# Generated by Django 5.1.2 on 2025-12-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_scorelog_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorelog',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', to='app.song'),
        ),
    ]
