# Generated by Django 5.1.2 on 2025-12-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_scorelog_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorelog',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='app.song'),
            preserve_default=False,
        ),
    ]
