# Generated by Django 5.1.2 on 2026-01-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_monthlymission_usermissionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymission',
            name='reward_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='reward_received',
            field=models.BooleanField(default=False),
        ),
    ]
