# Generated by Django 5.1.2 on 2026-01-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_monthlymission_reward_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermissionprogress',
            name='is_completed',
        ),
    ]
